import { initializeApp }
from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";

import {
  getAI,
  getGenerativeModel,
  GoogleAIBackend
} from "https://www.gstatic.com/firebasejs/12.18.0/firebase-ai.js";import * as pdfjsLib from "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs"; const firebaseConfig = {
  const firebaseConfig = {
  apiKey: "AIzaSyDYQrGYjmqbFWKDvhLFDbkfRjyt1ogcN7E",
  authDomain: "leitor-ia-69adc.firebaseapp.com",
  projectId: "leitor-ia-69adc",
  storageBucket: "leitor-ia-69adc.firebasestorage.app",
  messagingSenderId: "713448988376",
  appId: "1:713448988376:web:27c72bc82fd1cfc7f801ad",
  measurementId: "G-N2Y8L0Q88F"
};

// Inicializa o Firebase
const firebaseApp = initializeApp(firebaseConfig);

// Conecta ao Gemini Developer API
const ai = getAI(firebaseApp, {
  backend: new GoogleAIBackend()
});

// Modelo usado pelo Leitor IA
const model = getGenerativeModel(ai, {
  model: "gemini-3.7-flash"
});
pdfjsLib.GlobalWorkerOptions.workerSrc = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={pdf:null,page:1,pages:0,textByPage:{},refsByPage:{},notes:[],stripHeaders:true,compactRefs:true,original:false,dark:false};
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function loadPrefs(){try{const p=JSON.parse(localStorage.getItem('leitor-ia-prefs')||'{}');state.notes=JSON.parse(localStorage.getItem('leitor-ia-notes')||'[]');state.dark=!!p.dark;state.stripHeaders=p.stripHeaders!==false;state.compactRefs=p.compactRefs!==false;state.original=!!p.original;document.body.classList.toggle('dark',state.dark);$('#stripHeaders').checked=state.stripHeaders;$('#compactRefs').checked=state.compactRefs;$('#originalPage').checked=state.original;if(p.fontSize){$('#fontSize').value=p.fontSize;document.documentElement.style.setProperty('--reader-font',`${p.fontSize}px`)}if(p.lineHeight){$('#lineHeight').value=p.lineHeight;document.documentElement.style.setProperty('--reader-line',String(p.lineHeight/10))}}catch{}}
function savePrefs(){localStorage.setItem('leitor-ia-prefs',JSON.stringify({dark:state.dark,stripHeaders:state.stripHeaders,compactRefs:state.compactRefs,original:state.original,fontSize:Number($('#fontSize').value),lineHeight:Number($('#lineHeight').value)}))}
function detectReferences(lines){const refs=[],body=[];let inRefs=false;const head=/^(refer[eê]ncias|bibliografia|notas|notas de rodap[eé]|references|bibliography)\b/i;for(const raw of lines){const line=raw.trim();if(head.test(line)){inRefs=true;continue}const foot=/^(\[\d+\]|\d{1,3}[.)]\s|[¹²³⁴⁵⁶⁷⁸⁹⁰]+)\s*/.test(line);if(inRefs||foot){if(line.length>3)refs.push(line)}else body.push(raw)}return{body,refs}}
function stripHeaderFooter(lines){if(!state.stripHeaders||lines.length<8)return lines;const pageish=/^(p[aá]gina\s*)?\d+(\s*de\s*\d+)?$/i,short=s=>s.trim().length<70;let start=0,end=lines.length;if(lines[0]&&(pageish.test(lines[0].trim())||short(lines[0])))start=1;if(lines[1]&&pageish.test(lines[1].trim()))start=2;if(lines[end-1]&&(pageish.test(lines[end-1].trim())||short(lines[end-1])))end--;if(end>start&&lines[end-1]&&pageish.test(lines[end-1].trim()))end--;return lines.slice(start,end)}
function textToParagraphs(text){const lines=stripHeaderFooter(text.split('\n').map(x=>x.trim()).filter(Boolean));const{body,refs}=detectReferences(lines);const paras=[];let buf='';const heading=/^([A-ZÁÉÍÓÚÂÊÔÃÕÇ0-9][A-ZÁÉÍÓÚÂÊÔÃÕÇ0-9\s:–—-]{3,70})$/;for(const line of body){if(heading.test(line)&&line.length<72){if(buf){paras.push({type:'p',text:buf.trim()});buf=''}paras.push({type:'h',text:line});continue}buf+=(buf?' ':'')+line;if(buf.length>260){paras.push({type:'p',text:buf.trim()});buf=''}}if(buf)paras.push({type:'p',text:buf.trim()});return{paras,refs}}
async function getPageText(n){if(state.textByPage[n])return state.textByPage[n];const page=await state.pdf.getPage(n),content=await page.getTextContent(),byY=new Map();for(const item of content.items){const y=Math.round(item.transform?.[5]||0);if(!byY.has(y))byY.set(y,[]);byY.get(y).push(item)}const lines=[...byY.entries()].sort((a,b)=>b[0]-a[0]).map(([,items])=>items.sort((a,b)=>(a.transform?.[4]||0)-(b.transform?.[4]||0)).map(i=>i.str).join(' ')).filter(Boolean);return state.textByPage[n]=lines.join('\n').trim()}
async function renderOriginal(n){const page=await state.pdf.getPage(n),viewport=page.getViewport({scale:1.55}),canvas=$('#pdfCanvas'),ctx=canvas.getContext('2d');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:ctx,viewport}).promise}
async function renderPage(){if(!state.pdf)return;state.page=Math.max(1,Math.min(state.pages,state.page));$('#pageSlider').value=state.page;$('#pageLabel').textContent=`Página ${state.page} de ${state.pages}`;const text=await getPageText(state.page),{paras,refs}=textToParagraphs(text);state.refsByPage[state.page]=refs;$('#refsCount').textContent=refs.length;$('#refsDock').classList.toggle('hidden',refs.length===0);if(state.original){$('#cleanReader').classList.add('hidden');$('#canvasReader').classList.remove('hidden');await renderOriginal(state.page)}else{$('#canvasReader').classList.add('hidden');$('#cleanReader').classList.remove('hidden');const marker=refs.length&&state.compactRefs?` <button class="ref-marker" id="inlineRef">${refs.length}</button>`:'';$('#pageText').innerHTML=paras.map((p,i)=>p.type==='h'?`<p class="page-title">${esc(p.text)}</p>`:`<p>${esc(p.text)}${i===paras.length-1?marker:''}</p>`).join('')||'<p>Não foi possível extrair texto desta página. Use “Mostrar página original”.</p>';if($('#inlineRef'))$('#inlineRef').onclick=openRefs}window.scrollTo({top:0,behavior:'smooth'})}
async function openPdf(file){if(!file)return;const buf=await file.arrayBuffer();state.pdf=await pdfjsLib.getDocument({data:buf}).promise;state.pages=state.pdf.numPages;state.page=1;state.textByPage={};state.refsByPage={};$('#pageSlider').max=state.pages;$('#emptyState').classList.add('hidden');$('#readerView').classList.remove('hidden');await renderPage()}
function openRefs(){const refs=state.refsByPage[state.page]||[];$('#refsList').innerHTML=refs.length?refs.map((r,i)=>`<div class="ref-item"><b>${i+1}.</b> ${esc(r)}</div>`).join(''):'<div class="ref-item">Nenhuma referência identificada.</div>';$('#refsDialog').showModal()}
function closePanel(){$('#panel').classList.add('hidden');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view==='reader'))}
function openPanel(kind){if(kind==='reader')return closePanel();$('#panel').classList.remove('hidden');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===kind));if(kind==='notes')renderNotes();if(kind==='audio')renderAudio();if(kind==='ai')renderAI();if(kind==='search')renderSearch()}
function renderNotes(){$('#panelEyebrow').textContent='ANOTAÇÕES';$('#panelTitle').textContent=`Página ${state.page}`;$('#panelContent').innerHTML=`<div class="panel-card"><textarea id="noteText" placeholder="Escreva sua anotação..."></textarea><div class="panel-actions"><button id="saveNote" class="primary-btn">Salvar nota</button></div></div><div class="panel-card"><b>Notas salvas</b><div id="notesList"></div></div>`;$('#saveNote').onclick=()=>{const text=$('#noteText').value.trim();if(!text)return;state.notes.unshift({page:state.page,text,createdAt:new Date().toISOString()});localStorage.setItem('leitor-ia-notes',JSON.stringify(state.notes));renderNotes()};$('#notesList').innerHTML=state.notes.length?state.notes.map(n=>`<div class="note-item"><div class="note-meta">Página ${n.page} • ${new Date(n.createdAt).toLocaleString('pt-BR')}</div>${esc(n.text)}</div>`).join(''):'<div class="note-item">Nenhuma nota ainda.</div>'}
function currentText(){return state.textByPage[state.page]||''}
function renderAudio(){$('#panelEyebrow').textContent='AUDIOBOOK';$('#panelTitle').textContent='Leitura por voz';$('#panelContent').innerHTML=`<div class="panel-card"><div class="audio-controls"><button id="speak">▶ Ouvir</button><button id="pause">Ⅱ Pausar</button><button id="stop">■ Parar</button></div><label class="setting-row"><span>Velocidade</span><input id="rate" type="range" min="6" max="20" value="10"></label><label class="setting-row"><span>Voz</span><select id="voice"></select></label></div><div class="panel-card">Usa as vozes disponíveis no seu aparelho. Depois podemos integrar vozes neurais mais naturais.</div>`;const fill=()=>{$('#voice').innerHTML=speechSynthesis.getVoices().map((v,i)=>`<option value="${i}">${esc(v.name)} — ${esc(v.lang)}</option>`).join('')};fill();speechSynthesis.onvoiceschanged=fill;$('#speak').onclick=()=>{const text=currentText();if(!text)return alert('Abra um PDF primeiro.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text),vs=speechSynthesis.getVoices(),idx=Number($('#voice').value||0);if(vs[idx])u.voice=vs[idx];u.rate=Number($('#rate').value)/10;speechSynthesis.speak(u)};$('#pause').onclick=()=>speechSynthesis.paused?speechSynthesis.resume():speechSynthesis.pause();$('#stop').onclick=()=>speechSynthesis.cancel()}
function renderAI(){$('#panelEyebrow').textContent='ASSISTENTE IA';$('#panelTitle').textContent='Entender o documento';$('#panelContent').innerHTML=`<div class="panel-card"><div class="panel-actions"><button class="soft-btn" data-ai="Resumo">Resumir página</button><button class="soft-btn" data-ai="Explicação">Explicar simples</button><button class="soft-btn" data-ai="Perguntas">Criar perguntas</button></div></div><div class="panel-card"><textarea id="aiQ" placeholder="Pergunte algo sobre esta página..."></textarea><div class="panel-actions"><button id="askAI" class="primary-btn">Perguntar à IA</button></div></div><div id="aiAnswer" class="panel-card"><b>Integração pendente</b><p>O painel já está pronto. Para IA real, conectaremos um backend seguro; a chave não ficará exposta no navegador.</p></div>`;$$('[data-ai]').forEach(b=>b.onclick=()=>$('#aiAnswer').innerHTML=`<b>${b.dataset.ai}</b><p>Recurso preparado para integração com IA usando o texto desta página.</p>`);$('#askAI').onclick=()=>$('#aiAnswer').innerHTML='<b>Pergunta sobre o documento</b><p>Recurso preparado para a próxima etapa de integração com IA.</p>'}
function renderSearch(){$('#panelEyebrow').textContent='PESQUISA';$('#panelTitle').textContent='Pesquisar na internet';$('#panelContent').innerHTML=`<div class="panel-card"><input id="webQ" placeholder="Assunto para pesquisar..."><div class="panel-actions"><button id="googleBtn" class="primary-btn">Pesquisar no Google</button><button id="usePage" class="soft-btn">Usar texto da página</button></div></div><div class="panel-card">Agora a busca abre o Google. Depois podemos trazer resultados para dentro do app e resumir com IA.</div>`;$('#googleBtn').onclick=()=>{const q=$('#webQ').value.trim();if(q)window.open('https://www.google.com/search?q='+encodeURIComponent(q),'_blank','noopener')};$('#usePage').onclick=()=>$('#webQ').value=currentText().slice(0,240)}
$('#pdfInput').onchange=e=>openPdf(e.target.files?.[0]);$('#openPdfHero').onclick=()=>$('#pdfInput').click();$('#prevBtn').onclick=async()=>{if(state.page>1){state.page--;await renderPage()}};$('#nextBtn').onclick=async()=>{if(state.page<state.pages){state.page++;await renderPage()}};$('#pageSlider').oninput=async e=>{state.page=Number(e.target.value);await renderPage()};$('#refsBtn').onclick=openRefs;$('#refsClose').onclick=()=>$('#refsDialog').close();$('#settingsBtn').onclick=()=>$('#settingsDialog').showModal();$('#settingsClose').onclick=()=>$('#settingsDialog').close();$('#fontSize').oninput=e=>{document.documentElement.style.setProperty('--reader-font',`${e.target.value}px`);savePrefs()};$('#lineHeight').oninput=e=>{document.documentElement.style.setProperty('--reader-line',String(e.target.value/10));savePrefs()};$('#stripHeaders').onchange=async e=>{state.stripHeaders=e.target.checked;savePrefs();await renderPage()};$('#compactRefs').onchange=async e=>{state.compactRefs=e.target.checked;savePrefs();await renderPage()};$('#originalPage').onchange=async e=>{state.original=e.target.checked;savePrefs();await renderPage()};$('#themeBtn').onclick=()=>{state.dark=!state.dark;document.body.classList.toggle('dark',state.dark);savePrefs()};$('#closePanelBtn').onclick=closePanel;$$('.nav-btn').forEach(b=>b.onclick=()=>openPanel(b.dataset.view));$$('[data-panel]').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));$('#cleanBtn').onclick=async()=>{state.original=false;$('#originalPage').checked=false;savePrefs();await renderPage()};loadPrefs();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
